package gui;


import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;
import algorithms.Manager;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import detectors.ButterflyIdentifier;
import objects.Butterfly;

/**
 *
 * @author Shlomit Rozen(Gilboa) Haim Gilboa, Mayyan Simkins
 */
public class gui extends javax.swing.JFrame {

    private String _ImgPath = "";
    private String _Name = "";
    private String _Description = "";
    private FileNameExtensionFilter _fileFilter;
    private Manager _manager = new Manager();
    private String _pass = "12345";
    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        String [] Extensions = {"jpeg", "jpg", "bmp", "png", "tiff", "tif"};
        _fileFilter = new FileNameExtensionFilter("Images",Extensions);
        FChooser.setFileFilter(_fileFilter);
        resetGui();
    }

    private void resetGui()
    {
        btnSearch.setEnabled(false);
        btnAddToDB.setEnabled(false);
        jLabelpassword.setVisible(false);
        jPasswordField1.setVisible(false);
        btnPass.setVisible(false);
        jLabelButterflyName.setVisible(false);
        jTextFieldButterflyName.setVisible(false);
        btnAddDetails.setVisible(false);
        jLabelDescription.setVisible(false);
        taDescription.setVisible(false);
        jPasswordField1.setText("");
        jTextFieldButterflyName.setText("");
        taDescription.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FChooser = new javax.swing.JFileChooser();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnAddToDB = new javax.swing.JButton();
        jLabelpassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextFieldButterflyName = new javax.swing.JTextField();
        btnPass = new javax.swing.JButton();
        jLabelButterflyName = new javax.swing.JLabel();
        btnAddDetails = new javax.swing.JButton();
        jLabelDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Butterfly");
        setBounds(new java.awt.Rectangle(200, 100, 0, 0));
        setResizable(false);

        jTabbedPane2.setToolTipText("");

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAddToDB.setText("Add to DB");
        btnAddToDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToDBActionPerformed(evt);
            }
        });

        jLabelpassword.setText("Enter Password:");

        btnPass.setText("Apply Password");
        btnPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassActionPerformed(evt);
            }
        });

        jLabelButterflyName.setText("Butterfly Name");

        btnAddDetails.setText("Add Details");
        btnAddDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDetailsActionPerformed(evt);
            }
        });

        jLabelDescription.setText("Butterfly Description");

        taDescription.setColumns(20);
        taDescription.setLineWrap(true);
        taDescription.setRows(5);
        taDescription.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taDescription);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddToDB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldButterflyName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(btnBrowse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelpassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelButterflyName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescription, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddToDB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelpassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelButterflyName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldButterflyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDescription)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddDetails)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Butterfly Recognition", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Favorites", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("tabs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Image ScaleImage(Image img , int H, int W){
        BufferedImage Scaledimg = new BufferedImage(W, H, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = Scaledimg.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g.drawImage(img, 0, 0, W, H, null);
        g.dispose();
        return Scaledimg;
    }
    
    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        FChooser.showOpenDialog(jLabel1);
        File file = FChooser.getSelectedFile();
        if (file.exists()) {
            _ImgPath = file.getAbsolutePath();
        }
        try {
            BufferedImage UserImage = ImageIO.read(new File(_ImgPath));
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(ScaleImage(UserImage,jLabel1.getHeight(),jLabel1.getWidth()));
            jLabel1.setIcon(icon);
            btnSearch.setEnabled(true);
            btnAddToDB.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        	System.out.println(_ImgPath);
        	
        	BufferedImage image = null;
			try {
				image = ImageIO.read(new File(_ImgPath));
			} catch (IOException e) {
				e.printStackTrace();
			}

        	ButterflyIdentifier bi = new ButterflyIdentifier();
            BufferedImage filteredImage = bi.getFilteredImage(image);
        	
            // take the buffered image and insert to the algorithm
            
        	Butterfly ans = _manager.getClosestImage(bi.getRGBMean(filteredImage));
            
            SearchResView showAns = new SearchResView();
            showAns.setButterflyAns(filteredImage);
            //showAns.setButterflyAns(ans);

        //SearchResView showAns = new SearchResView();
        //showAns.setButterflyAns(new Butterfly(_Name,"C:\\Users\\שלומית\\Documents\\butterfly_images\\1138682009428191446.jpg", _Description));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddToDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToDBActionPerformed
        jLabelpassword.setVisible(true);
        jPasswordField1.setVisible(true);
        btnPass.setVisible(true);
        btnBrowse.setEnabled(false);
        btnSearch.setEnabled(false);
        btnAddToDB.setEnabled(false);
    }//GEN-LAST:event_btnAddToDBActionPerformed

    private void btnPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassActionPerformed
        char[] userpass = jPasswordField1.getPassword();
        String Upass = "";
        for (int i = 0; i < userpass.length; i++)
        {
            Upass = Upass + userpass[i];
        }
        if (_pass.equalsIgnoreCase(Upass))
        {
            jLabelpassword.setVisible(false);
            jPasswordField1.setVisible(false);
            btnPass.setVisible(false);
            jLabelButterflyName.setVisible(true);
            jTextFieldButterflyName.setVisible(true);
            btnAddDetails.setVisible(true);
            jLabelDescription.setVisible(true);
            taDescription.setVisible(true);
        }
        
    }//GEN-LAST:event_btnPassActionPerformed

    private void btnAddDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDetailsActionPerformed
        _Name = jTextFieldButterflyName.getText();
        _Description = taDescription.getText();
        _ImgPath = convertBackslashes(_ImgPath);
        try{
            if (!_Description.isEmpty() && !_Name.isEmpty())
            {
                _manager.AddToDB(_ImgPath, _Name,_Description);
                JOptionPane.showMessageDialog(null, "Butterfly added to Data Base", "Add butterfly", JOptionPane.INFORMATION_MESSAGE);
                resetGui();
                btnBrowse.setEnabled(true);
                btnSearch.setEnabled(true);
                btnAddToDB.setEnabled(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Some fields are empty, can't add data to the data base", "Missing Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch (ClassNotFoundException | SQLException | IOException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "an error occured while adding the data \n Reason: \n " + e.getMessage(), "Add to data base failed", JOptionPane.ERROR_MESSAGE);
            resetGui();
            btnBrowse.setEnabled(true);
            btnSearch.setEnabled(true);
            btnAddToDB.setEnabled(true);
        }       
    }//GEN-LAST:event_btnAddDetailsActionPerformed

	public static String convertBackslashes(String s){
		String res = s.replace("\t", "/t");
		res = res.replace("\r", "/r");
		res = res.replace("\n", "/n");
		res = res.replace("\b", "/b");
		res = res.replace("\f", "/f");
		res = res.replace("\\", "/");
		System.out.println(res);
		return res;
	}
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FChooser;
    private javax.swing.JButton btnAddDetails;
    private javax.swing.JButton btnAddToDB;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnPass;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelButterflyName;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelpassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldButterflyName;
    private javax.swing.JTextArea taDescription;
    // End of variables declaration//GEN-END:variables

}
